
version: 2

models:
  - name: products  # This corresponds to the model file name
    description: "Model that inserts new product data into devdw.Products"
    columns:
      - name: src_productCode
        description: "The unique product code for each product."
        tests:
          - not_null
          - unique
      - name: productName
        description: "The name of the product."
      - name: productLine
        description: "The product's line category."
      - name: productScale
        description: "The scale or size of the product."
      - name: productVendor
        description: "The vendor of the product."
      - name: productDescription
        description: "A detailed description of the product."
      - name: quantityInStock
        description: "The quantity of the product currently in stock."
      - name: buyPrice
        description: "The buying price of the product."
      - name: MSRP
        description: "The manufacturer's suggested retail price."
      - name: dw_product_line_id
        description: "Foreign key reference to the product line."
      - name: create_timestamp
        description: "Timestamp when the product was created."
      - name: update_timestamp
        description: "Timestamp when the product was last updated."
      - name: etl_batch_no
        description: "The batch number associated with the ETL process."
      - name: etl_batch_date
        description: "The date when the ETL process was run."
