version: 2

sources:
  - name: etl_metadata
    schema: etl_metadata
    tables:
      - name: batch_control
        columns: 
          - name: etl_batch_no
          - name: etl_batch_date

  - name: devstage
    schema: devstage
    tables:
      - name: ProductLines
        columns:
          - name: productline
          - name: create_timestamp
          - name: update_timestamp

      - name: Products
        columns:
          - name: productCode
          - name: productName
          - name: productLine
          - name: productScale
          - name: productVendor
          - name: quantityInStock
          - name: buyPrice
          - name: MSRP
          - name: create_timestamp
          - name: update_timestamp