tables = {
    'OFFICES': ['OFFICECODE', 'CITY', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'STATE', 'COUNTRY', 'POSTALCODE', 'TERRITORY'],
    'EMPLOYEES': ['EMPLOYEENUMBER', 'LASTNAME', 'FIRSTNAME', 'EXTENSION', 'EMAIL', 'OFFICECODE', 'REPORTSTO', 'JOBTITLE'],
    'CUSTOMERS': ['CUSTOMERNUMBER', 'CUSTOMERNAME', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'SALESREPEMPLOYEENUMBER', 'CREDITLIMIT'],
    'ORDERS': ['ORDERNUMBER', 'ORDERDATE', 'REQUIREDDATE', 'SHIPPEDDATE', 'STATUS', 'COMMENTS', 'CUSTOMERNUMBER'],
    'ORDERDETAILS': ['ORDERNUMBER', 'PRODUCTCODE', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER'],
    'PRODUCTS': ['PRODUCTCODE', 'PRODUCTNAME', 'PRODUCTLINE', 'PRODUCTSCALE', 'PRODUCTVENDOR', 'PRODUCTDESCRIPTION', 'QUANTITYINSTOCK', 'BUYPRICE', 'MSRP'],
    'PRODUCTLINES': ['PRODUCTLINE', 'TEXTDESCRIPTION', 'HTMLDESCRIPTION', 'IMAGE'],
    'PAYMENTS': ['CUSTOMERNUMBER', 'CHECKNUMBER', 'PAYMENTDATE', 'AMOUNT']
}

