tables = {
    'OFFICES': ['OFFICECODE', 'CITY', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'STATE', 'COUNTRY', 'POSTALCODE', 'TERRITORY', 'CREATE_TIMESTAMP', 'UPDATE_TIMESTAMP'],
    'EMPLOYEES': ['EMPLOYEENUMBER', 'LASTNAME', 'FIRSTNAME', 'EXTENSION', 'EMAIL', 'OFFICECODE', 'REPORTSTO', 'JOBTITLE', 'CREATE_TIMESTAMP', 'UPDATE_TIMESTAMP'],
    'CUSTOMERS': ['CUSTOMERNUMBER', 'CUSTOMERNAME', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'SALESREPEMPLOYEENUMBER', 'CREDITLIMIT',  'CREATE_TIMESTAMP', 'UPDATE_TIMESTAMP'],
    'ORDERS': ['ORDERNUMBER', 'ORDERDATE', 'REQUIREDDATE', 'SHIPPEDDATE', 'STATUS', 'CUSTOMERNUMBER', 'CREATE_TIMESTAMP', 'UPDATE_TIMESTAMP'],
    'ORDERDETAILS': ['ORDERNUMBER', 'PRODUCTCODE', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'CREATE_TIMESTAMP', 'UPDATE_TIMESTAMP'],
    'PRODUCTS': ['PRODUCTCODE', 'PRODUCTNAME', 'PRODUCTLINE', 'PRODUCTSCALE', 'PRODUCTVENDOR', 'QUANTITYINSTOCK', 'BUYPRICE', 'MSRP', 'CREATE_TIMESTAMP', 'UPDATE_TIMESTAMP'],
    'PRODUCTLINES': ['PRODUCTLINE', 'CREATE_TIMESTAMP', 'UPDATE_TIMESTAMP'],
    'PAYMENTS': ['CUSTOMERNUMBER', 'CHECKNUMBER', 'PAYMENTDATE', 'AMOUNT', 'CREATE_TIMESTAMP', 'UPDATE_TIMESTAMP']
}